<?php
$topic = str_replace(" :)"," <img src=\"smiles/1.gif\" alt=\" :)\"/> ",$topic);
$topic = str_replace(" :D"," <img src=\"smiles/2.gif\" alt=\" :D\"/> ",$topic);
$topic = str_replace(" =)"," <img src=\"smiles/3.gif\" alt=\" =)\"/> ",$topic);
$topic = str_replace(" :P"," <img src=\"smiles/4.gif\" alt=\" :P\"/> ",$topic);
$topic = str_replace(" :("," <img src=\"smiles/5.gif\" alt=\" :(\"/> ",$topic);
$topic = str_replace(" :*"," <img src=\"smiles/6.gif\" alt=\" :*\"/> ",$topic);
$topic = str_replace(" :sex"," <img src=\"smiles/7.gif\" alt=\" :sex\"/> ",$topic);
$topic = str_replace(" :fuck1"," <img src=\"smiles/8.gif\" alt=\" :fuck1\"/> ",$topic);
$topic = str_replace(" :ne1"," <img src=\"smiles/9.gif\" alt=\" :ne1\"/> ",$topic);
$topic = str_replace(" :lol"," <img src=\"smiles/10.gif\" alt=\" :lol\"/> ",$topic);
$topic = str_replace(" :A"," <img src=\"smiles/11.gif\" alt=\" :A\"/> ",$topic);
$topic = str_replace(" :B","
 <img src=\"smiles/12.gif\" alt=\" :B\"/> ",$topic);
$topic = str_replace(" :O"," <img src=\"smiles/13.gif\" alt=\" :O\"/> ",$topic);
$topic = str_replace(" ;)"," <img src=\"smiles/14.gif\" alt=\" ;)\"/> ",$topic);
$topic = str_replace(" =D"," <img src=\"smiles/15.gif\" alt=\" =D\"/> ",$topic);
$topic = str_replace(" :good"," <img src=\"smiles/16.gif\" alt=\" :good\"/> ",$topic);
$topic = str_replace(" :rofl"," <img src=\"smiles/17.gif\" alt=\" :rofl\"/> ",$topic);
$topic = str_replace(" :xi"," <img src=\"smiles/18.gif\" alt=\" :xi\"/> ",$topic);
$topic = str_replace(" :piktas"," <img src=\"smiles/19.gif\" alt=\" :piktas\"/> ",$topic);
$topic = str_replace(" :N"," <img src=\"smiles/20.gif\" alt=\" :N\"/> ",$topic);
$topic = str_replace(" :box"," <img src=\"smiles/21.gif\" alt=\" :box\"/> ",$topic); 
$topic = str_replace(" :geda"," <img src=\"smiles/22.gif\" alt=\" :geda\"/> ",$topic); 
$topic = str_replace(" :mojuoja"," <img src=\"smiles/23.gif\" alt=\" :mojuoja\"/> ",$topic); 
$topic = str_replace(" :cry"," <img src=\"smiles/24.gif\" alt=\" :cry\"/> ",$topic); 
$topic = str_replace(" :pasikeles"," <img src=\"smiles/25.gif\" alt=\" :pasikeles\"/> ",$topic); 
$topic = str_replace(" :?"," <img src=\"smiles/26.gif\" alt=\" :?\"/> ",$topic); 
$topic = str_replace(" :ploja"," <img src=\"smiles/27.gif\" alt=\" :ploja\"/> ",$topic); 
$topic = str_replace(" :flood"," <img src=\"smiles/28.gif\" alt=\" :flood\"/> ",$topic); 
$topic = str_replace(" :ha"," <img src=\"smiles/29.gif\" alt=\" :ha\"/> ",$topic); 
$topic = str_replace(" :yay"," <img src=\"smiles/30.gif\" alt=\" :yay\"/> ",$topic); 
$topic = str_replace(" :yes"," <img src=\"smiles/31.gif\" alt=\" :yes\"/> ",$topic); 
$topic = str_replace(" :aga"," <img src=\"smiles/32.gif\" alt=\" :aga\"/> ",$topic); 
$topic = str_replace(" :ciki"," <img src=\"smiles/33.gif\" alt=\" :ciki\"/> ",$topic); 
$topic = str_replace(" :liudnas"," <img src=\"smiles/34.gif\" alt=\" :liudnas\"/> ",$topic); 
$topic = str_replace(" :graso"," <img src=\"smiles/35.gif\" alt=\" :graso\"/> ",$topic); 
$topic = str_replace(" :/"," <img src=\"smiles/36.gif\" alt=\" :/\"/> ",$topic); 
$topic = str_replace(" :cool"," <img src=\"smiles/37.gif\" alt=\" :cool\"/> ",$topic); 
$topic = str_replace(" :gun"," <img src=\"smiles/38.gif\" alt=\" :gun\"/> ",$topic); 
$topic = str_replace(" :Z"," <img src=\"smiles/39.gif\" alt=\" :Z\"/> ",$topic); 
$topic = str_replace(" :roze"," <img src=\"smiles/40.gif\" alt=\" :roze\"/> ",$topic); 
$topic = str_replace(" :yee"," <img src=\"smiles/41.gif\" alt=\" :yee\"/> ",$topic); 
$topic = str_replace(" :welcome"," <img src=\"smiles/42.gif\" alt=\" :welcome\"/> ",$topic); 
$topic = str_replace(" :@"," <img src=\"smiles/43.gif\" alt=\" :@\"/> ",$topic); 

$topic = str_replace(" :fight"," <img src=\"smiles/44.gif\" alt=\" :fight\"/> ",$topic); 
$topic = str_replace(" :vemiu"," <img src=\"smiles/45.gif\" alt=\" :vemiu\"/> ",$topic); 
$topic = str_replace(" :stiprus"," <img src=\"smiles/46.gif\" alt=\" :stiprus\"/> ",$topic); 
$topic = str_replace(" :hug"," <img src=\"smiles/47.gif\" alt=\" :hug\"/> ",$topic); 
$topic = str_replace(" :kuklus"," <img src=\"smiles/48.gif\" alt=\" :kuklus\"/> ",$topic); 
$topic = str_replace(" :nuobodu"," <img src=\"smiles/49.gif\" alt=\" 
:nuobodu\"/> ",$topic); 
$topic = str_replace(" 3/"," <img src=\"smiles/50.gif\" alt=\" 3/\"/> ",$topic); 
$topic = str_replace(" :devil"," <img src=\"smiles/51.gif\" alt=\" :devil\"/> ",$topic); 
$topic = str_replace(" :smoke"," <img src=\"smiles/52.gif\" alt=\" :smoke\"/> ",$topic); 
$topic = str_replace(" :nono"," <img src=\"smiles/53.gif\" alt=\" :nono\"/> ",$topic); 
$topic = str_replace(" :kvaily"," <img src=\"smiles/54.gif\" alt=\" :kvaily\"/> ",$topic); 
$topic = str_replace(" :fuck2"," <img src=\"smiles/55.gif\" alt=\" :fuck2\"/> ",$topic); 
$topic = str_replace(" :sirdis"," <img src=\"smiles/56.gif\" alt=\" :sirdis\"/> ",$topic); 
$topic = str_replace(" :nustebes"," <img src=\"smiles/57.gif\" alt=\" :nustebes\"/> ",$topic); 
$topic = str_replace(" :kiss"," <img src=\"smiles/58.gif\" alt=\" :kiss\"/> ",$topic); 
$topic = str_replace(" =/"," <img src=\"smiles/59.gif\" alt=\" =/\"/> ",$topic); 
$topic = str_replace(" :ne2"," <img src=\"smiles/60.gif\" alt=\" :ne2\"/> ",$topic); 
$topic = str_replace(" :neas"," <img src=\"smiles/61.gif\" alt=\" :neas\"/> ",$topic); 
$topic = str_replace(" :skanu"," <img src=\"smiles/62.gif\" alt=\" :skanu\"/> ",$topic); 
$topic = str_replace(" :ok"," <img src=\"smiles/63.gif\" alt=\" :ok\"/> ",$topic); 
$topic = str_replace(" :svajingas"," <img src=\"smiles/64.gif\" alt=\" :svajingas\"/> ",$topic); 
$topic = str_replace(" :iesko"," <img src=\"smiles/65.gif\" alt=\" :iesko\"/> ",$topic); 
$topic = str_replace(" :sorry"," <img src=\"smiles/66.gif\" alt=\" :sorry\"/> ",$topic); 
$topic = str_replace(" :stink"," <img src=\"smiles/67.gif\" alt=\" :stink\"/> ",$topic); 
$topic = str_replace(" :love"," <img src=\"smiles/68.gif\" alt=\" :love\"/> ",$topic); 
?>